sonar.projectKey=bee-san_Japanese_Character_Name_Dictionary
sonar.organization=bee-san

sonar.projectName=Japanese_Character_Name_Dictionary
sonar.sourceEncoding=UTF-8

sonar.sources=yomitan-dict-builder/src,yomitan-dict-builder/static,yomitan-dict-builder/scripts
sonar.tests=yomitan-dict-builder/tests
sonar.exclusions=**/target/**,**/*.min.js,yomitan-dict-builder/static/data/**,yomitan-dict-builder/data/**,yomitan-dict-builder/config/**,yomitan-dict-builder/tests/fixtures/**,**/*.log
